name: (PR) Check Conventional Commits

on:
  pull_request

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dkhunt27/action-conventional-commits@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}